package Interface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import Aplicação.Dados;
import Persistência.Cliente;
import Persistência.Fornecedor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Marri
 */
public class CadastroFornecedor extends BaseFrame implements ActionListener {

    public CadastroFornecedor(Fornecedor c) {
        atual = c;
        EhCadastro = false;
        initComponents();

        textCod.setText(c.getCod());
        textNome.setText(c.getNome());
        textCNPJ.setText(c.getCnpj());
        textTelefone.setText(c.getTel());
        textEmail.setText(c.getEmail());
        textBairro.setText(c.getBairro());
        textLogradouro.setText(c.getLogradouro());
        textCom.setText(c.getComp());
        textCEP.setText(c.getCep());
        textCidade.setText(c.getCidade());
        textUF.setText(c.getUf());

    }

    public CadastroFornecedor() {
        atual = new Fornecedor();
        EhCadastro = true;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelCodFun = new javax.swing.JLabel();
        labelNomeFun = new javax.swing.JLabel();
        labelCNPJ = new javax.swing.JLabel();
        textCNPJ = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textCod = new javax.swing.JTextField();
        labelDP = new javax.swing.JLabel();
        labelEn = new javax.swing.JLabel();
        labelLo = new javax.swing.JLabel();
        textLogradouro = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        textBairro = new javax.swing.JTextField();
        labelCom = new javax.swing.JLabel();
        textCom = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        labelUF = new javax.swing.JLabel();
        textUF = new javax.swing.JTextField();
        labelCEP = new javax.swing.JLabel();
        textCEP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        buttonCan = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();

        setTitle("Cadastro de Fornecedor");
        setBackground(new java.awt.Color(255, 204, 204));

        labelCodFun.setText("** Codigo: ");

        labelNomeFun.setText("** Nome da empresa: ");

        labelCNPJ.setText("** CNPJ: ");

        textCod.setVerifyInputWhenFocusTarget(false);

        labelDP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDP.setText("Dados da Empresa: ");

        labelEn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEn.setText("** Endereco:");

        labelLo.setText("** Logradouro: ");

        labelBairro.setText("** Bairro: ");

        labelCom.setText("** Complemento: ");

        labelCidade.setText("** Cidade: ");

        labelUF.setText("** UF: ");

        labelCEP.setText("** CEP: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Contato: ");

        labelTel.setText("Telefone: ");

        labelEmail.setText("E-mail: ");

        buttonCan.setText("CANCELAR");
        buttonCan.addActionListener(this);

        buttonSalvar.setText("SALVAR");
        buttonSalvar.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(
                                                labelLo)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                textLogradouro,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                239,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0,
                                                0,
                                                Short.MAX_VALUE))
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addGap(0,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(
                                                buttonCan)
                                        .addGap(49, 49,
                                                49)
                                        .addComponent(
                                                buttonSalvar)
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(
                                                labelTel)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                textTelefone,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                127,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                labelEmail)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                .addComponent(
                                                        textEmail,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        241,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                        .addComponent(
                                                                labelUF)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                textUF,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                324,
                                                                Short.MAX_VALUE)))
                                        .addGap(0,
                                                0,
                                                Short.MAX_VALUE))
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        jLabel1)
                                                .addComponent(
                                                        labelDP)
                                                .addComponent(
                                                        labelEn)
                                                .addComponent(
                                                        labelCodFun))
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addGroup(
                                                layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(
                                                        layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                .addGap(77,
                                                                        77,
                                                                        77)
                                                                .addComponent(
                                                                        textCod,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        114,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        labelCNPJ)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(
                                                                        textCNPJ,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        166,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(
                                                                                labelCom)
                                                                        .addComponent(
                                                                                labelCEP))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(
                                                                                textCEP,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(
                                                                                textCom,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                145,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(58,
                                                                        58,
                                                                        58)
                                                                .addComponent(
                                                                        labelCidade)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                        .addGroup(
                                                                                layout.createSequentialGroup()
                                                                                .addComponent(
                                                                                        labelBairro)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(
                                                                                        textBairro,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        106,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(
                                                                                textCidade))))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                        .addComponent(
                                                                labelNomeFun)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(
                                                                textNome,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                377,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)))));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(labelDP)
                        .addGap(27, 27, 27)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCodFun)
                                .addComponent(
                                        textCod,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCNPJ)
                                .addComponent(
                                        textCNPJ,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelNomeFun)
                                .addComponent(
                                        textNome,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelEn)
                        .addGap(28, 28, 28)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelLo)
                                .addComponent(
                                        textLogradouro,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelBairro)
                                .addComponent(
                                        textBairro,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCom)
                                .addComponent(
                                        textCom,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCidade)
                                .addComponent(
                                        textCidade,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCEP)
                                .addComponent(
                                        textCEP,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUF)
                                .addComponent(
                                        textUF,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTel)
                                .addComponent(
                                        textTelefone,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelEmail)
                                .addComponent(
                                        textEmail,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                37, Short.MAX_VALUE)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonCan)
                                .addComponent(buttonSalvar))
                        .addGap(20, 20, 20)));

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton buttonCan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textLogradouro;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCNPJ;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCodFun;
    private javax.swing.JLabel labelCom;
    private javax.swing.JLabel labelDP;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEn;
    private javax.swing.JLabel labelLo;
    private javax.swing.JLabel labelNomeFun;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelUF;
    private javax.swing.JTextField textBairro;
    private javax.swing.JTextField textCEP;
    private javax.swing.JTextField textCNPJ;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCod;
    private javax.swing.JTextField textCom;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JTextField textUF;

    Fornecedor atual;
    boolean EhCadastro;

    // End of variables declaration
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == buttonSalvar) {

            if ((textNome.getText().length() == 0)
                    || (textCNPJ.getText().length() == 0)
                    || (textCod.getText().length() == 0)
                    || (textLogradouro.getText().length() == 0)
                    || (textCEP.getText().length() == 0)
                    || (textCidade.getText().length() == 0)
                    || (textUF.getText().length() == 0)) {

                JOptionPane.showMessageDialog(null,
                        "Digite os campos obrigatorios **");
                return;
            } else {
                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso");
            }

            atual.setNome(textNome.getText());
            atual.setCod(textCod.getText());
            atual.setCnpj(textCNPJ.getText());
            atual.setTel(textTelefone.getText());
            atual.setEmail(textEmail.getText());
            atual.setLogradouro(textLogradouro.getText());
            atual.setComp(textCom.getText());
            atual.setCep(textCEP.getText());
            atual.setCidade(textCidade.getText());
            atual.setUf(textUF.getText());
            atual.setBairro(textBairro.getText());

            if (EhCadastro) {
                Dados.addFornecedor(atual);
            } else {
                try {
                    Dados.GravarFornecedores();
                } catch (IOException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
            this.setVisible(false);
        }
        if (e.getSource() == buttonCan) {
            this.setVisible(false);
        }

    }
}
